[package]
name = "gen_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
ripper = { path = "../ripper" }
anyhow = "1.0"
structopt = "*"
prettyplease = "0.1.18"
